swagger: '2.0'
info:
  title: ZMON SLO Metrics
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the HTTP_TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /health:
    get:
      tags: [System]
      operationId: app.get_health
      summary: Return health
      security: []
      responses:
        200:
          description: Health is OK
  /products:
    get:
      tags: [SLO]
      operationId: app.get_products
      responses:
        200:
          description: List of products
          examples:
            "application/json":
                - id: 123
                  name: "E-Coin"
  /service-level-indicators/{product}/{name}:
    get:
      tags: [SLO]
      operationId: app.get_service_level_indicators
      parameters:
        - name: product
          in: path
          type: string
          required: true
        - name: name
          in: path
          type: string
          required: true
        - name: time_from
          in: query
          type: string
        - name: time_to
          in: query
          type: string
      responses:
        200:
          description: Return SLIs
  /service-level-indicators/{product}/{name}/update:
    post:
      tags: [SLO]
      operationId: app.post_update
      summary: Update
      parameters:
        - name: product
          in: path
          type: string
          required: true
        - name: name
          in: path
          type: string
          required: true
        - name: body
          in: body
          schema:
            type: object
            properties:
              start:
                type: integer
                default: 5
              time_unit:
                type: string
                default: minutes
            additionalProperties: true

      responses:
        200:
          description: Update successful
  /service-level-objectives/{product}:
    get:
      tags: [SLO]
      operationId: app.get_service_level_objectives
      parameters:
        - name: product
          in: path
          type: string
          required: true
      responses:
        200:
          description: Return SLO definitions
  /service-level-objectives/{product}/update:
    post:
      tags: [SLO]
      operationId: app.update_service_level_objectives
      parameters:
        - name: product
          in: path
          type: string
          required: true
      responses:
        200:
          description: Update SLIs
  /service-level-objectives/{product}/reports/{report_type}:
    get:
      tags: [SLO]
      operationId: app.get_service_level_objective_report
      parameters:
        - name: product
          in: path
          type: string
          required: true
        - name: report_type
          in: path
          type: string
          required: true
      responses:
        200:
          description: Return report data

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
